### ISSUE TITLE
Convert fisheye image to an equirectangular image

### ISSUE THREAD

**Issue by echo-gui** [matsuren/dscamera#1]
Hi, this is a very useful lib for double sphere camera model.

I noticed that when the algorithm coverts fisheye image to equirectangular image, it first calculate the 3D points maps to image plane. I really interested about this method, can you provide some theoretical basis for this method? 

Besides, is this process reversible? If I transform the equirectangular image to fisheye image, is the fisheye image same as the original fisheye image?

**Comment by matsuren** [comment]
Thank you for the comment. 

It just converts bearing angle (3D point) into pixel location. So you can look at camera projection model for theoretical basis.

It can be used for converting fisheye image into an equirectangular image if fisheye image has enough resolution. You can check my another library, which uses OcamCalib, for example.
https://github.com/matsuren/ocamcalib_undistort/blob/master/examples/undistort_sample.ipynb

Thanks,

**Comment by echo-gui** [comment]
Thanks for your answer. I checked the equirectangular projection in Wikipedia and double sphere camera model, and your solution with double sphere camera really helps to transform the fisheye image.

Recently, I try to do the plane sweeping algorithm in fisheye image. I saw your papers about *Octave Deep Plane-sweeping Network* and *360° Depth Estimation from Multiple Fisheye Images*. These are very impressive works on fisheye depth estimation.

The results I got from plane sweeping algorithm on fisheye images has lots of artifacts. The result depth maps were not as continuous as expected. As you have down great jobs on fisheye images and depth estimation, do you have any advice on plane sweeping algorithm?

I really appreciate your attention, thank you!

**Comment by matsuren** [comment]
I'm glad that you saw my papers. I can't tell you anything without enough information, but regularization of cost volume might be important in some cases to decrease artifacts.

Thanks,

**Comment by matsuren** [comment]
Closing now. Let me know if you have additional questions.
